### ISSUE TITLE
'CREATE TRIGGER' 必须是查询批次中的第一个语句。

### ISSUE THREAD

**Issue by hailang2ll** [zhaopeiym/quartzui#11]
消息 111，级别 15，状态 1，第 65 行
'CREATE TRIGGER' 必须是查询批次中的第一个语句。
消息 111，级别 15，状态 1，第 93 行
'CREATE TRIGGER' 必须是查询批次中的第一个语句。
消息 111，级别 15，状态 1，第 111 行
'CREATE TRIGGER' 必须是查询批次中的第一个语句。
消息 111，级别 15，状态 1，第 128 行
'CREATE TRIGGER' 必须是查询批次中的第一个语句。

**Comment by zhaopeiym** [comment]
请问 你这是在运行docker的时候报错吗？

docker run -v /fileData/quartzuifile:/app/File  --restart=unless-stopped --privileged=true --name quartzui -dp 5088:80 bennyzhao/quartzui

**Comment by hailang2ll** [comment]
执行tables_sqlite.sql报的错，目前用的sqlserver
界面怎么运行起来，里面Index文件为空吗？

**Comment by zhaopeiym** [comment]
1、首先这是前后端分离的方式，前端用的Angular,
2、Angular 的运行命令 ng serve -o
3、sqlserver的方式需要自己尝试，我直接用的SQLite，完全够了。
4、如果只是简单使用，建议直接用docker方式，省去了折腾。

**Comment by hailang2ll** [comment]
里面的前端页面没有源码吗？

**Comment by zhaopeiym** [comment]
有的。
https://github.com/zhaopeiym/quartzui/tree/master/QuartzNetWeb
这个目录下就是前端的Angular项目。
