### ISSUE TITLE
新建任务失败

### ISSUE THREAD

**Issue by DUWENINK** [zhaopeiym/quartzui#15]
![撒打算打算](https://user-images.githubusercontent.com/16337239/59361822-0a910400-8d65-11e9-8695-64ac1d7890bb.gif)
我录制了动图,如图所致

**Comment by zhaopeiym** [comment]
![image](https://user-images.githubusercontent.com/5820324/59394860-e577b200-8db3-11e9-87ea-9ab16bce4217.png)


你能把你添加的所有参数贴出来吗？谢谢。

**Comment by zhaopeiym** [comment]
你想要的表达式是 ：每周1、2、3、4、5 的10点、10:44、22点、22:44 ?  

那么表达式应该是：0 0,44 10,22 ? * 2,3,4,5,6  

![image](https://user-images.githubusercontent.com/5820324/59395815-62a52600-8db8-11e9-917d-1cdc4853dfd4.png)

可以看看常用Cron表达式：https://www.pppet.net/changyong  
和Cron表达式教程：https://www.pppet.net/jiaocheng

**Comment by DUWENINK** [comment]
谢谢,的确是cron表达式的问题,我的cron表达式实在那个网址上勾选生成的吗最后没有注意
