### ISSUE TITLE
哪个版本比较稳健

### ISSUE THREAD

**Issue by hellozhang** [zhaopeiym/quartzui#18]
各个版本区别是什么

**Comment by zhaopeiym** [comment]
你指的是docker？

**Comment by hellozhang** [comment]
Master  dev

**Comment by hellozhang** [comment]
主要生产的建议哪个版本

**Comment by zhaopeiym** [comment]
肯定是 Master

**Comment by zhaopeiym** [comment]
dev是开发分支，经过使用 验证后才合并到master

**Comment by hellozhang** [comment]
:"不知道这样的主机。 at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n at System.Threading.Tasks.ValueTask`1.get_Result()\r\n at

**Comment by hellozhang** [comment]
日志里面
