### ISSUE TITLE
我想请教一个问题

### ISSUE THREAD

**Issue by someon2** [zhaopeiym/quartzui#19]
我想请教一个问题，就是我执行的任务可能时间比较长半小时，十几分钟的都会有,怎么回调接收任务执行结果，比如说任务的执行结果，执行过程日志，执行发生异常等情况，保存到这个任务系统里

**Comment by zhaopeiym** [comment]
长时间的任务适合做成异步，不然会超时。

**Comment by someon2** [comment]
怎么回传给异步系统结果呢？

**Comment by someon2** [comment]
比如同步的请求执行完返回结果这边系统记录，如果是异步的怎么回传结果？

**Comment by zhaopeiym** [comment]
异步的话，返回结果就直接记录到请求目标的机器上。
