### ISSUE TITLE
 提供I18N的位置功能  / Provide the feature of Localización for I18N 

### ISSUE THREAD

**Issue by portal7** [zhaopeiym/quartzui#21]
它非常有用，可以提供将标签文本翻译为资源的能力。

**Comment by Ran-snow** [comment]
@zhaopeiym 有国外网友请求支持多语言啦。 Support multiple languages.

**Comment by zhaopeiym** [comment]
@Ran-snow @portal7 
![QQ截图20191001105540](https://user-images.githubusercontent.com/5820324/65930902-14389780-e43a-11e9-9869-3efa2d61c4fd.png)
