### ISSUE TITLE
怎么做到开机启动的

### ISSUE THREAD

**Issue by wanghaoxing** [zhaopeiym/quartzui#24]
目前看了下示例,是把schedulecenter注册成单例的,每次一调用就start了,如何做到重启以后自动start

**Comment by zhaopeiym** [comment]
我现在的做法是，手动调用一次（在浏览器里面访问一次）。或者可以用crontab 定时访问。

**Comment by wanghaoxing** [comment]
crontab 定时访问方式能具体说下怎么实现吗?比如后台起一个IHostedService定时这样吗..

**Comment by taadis** [comment]
@wanghaoxing 如果只是要个能够开机启动的的quartz 和 crontabl 调度服务的话，可以看看我这个实例 [taadis/h2o](https://gitee.com/taadis/h2o) ...

**Comment by zhaopeiym** [comment]
Linux crontab  @wanghaoxing

**Comment by wanghaoxing** [comment]
谢谢各位了解了
