### ISSUE TITLE
任务不执行

### ISSUE THREAD

**Issue by 846677234** [zhaopeiym/quartzui#3]
任务执行到某天后，之后就不再执行了，看docker日志没有发现异常。只有我一直打开页面才会正常执行
![qq 20180718095902](https://user-images.githubusercontent.com/6667502/42855037-394e7040-8a71-11e8-936d-96f6b5161357.png)

**Comment by zhaopeiym** [comment]
可以看到日志吗？
![qq 20180718100447](https://user-images.githubusercontent.com/5820324/42855215-02d6cc3c-8a72-11e8-8843-2dddadaa18b1.png)

和页面是否打开应该是没有关系的。

**Comment by 846677234** [comment]
![image](https://user-images.githubusercontent.com/6667502/42855287-698e9f86-8a72-11e8-891b-dd269b32b2e7.png)
日志到7/7后面就没有了，手动执行可以成功

**Comment by zhaopeiym** [comment]
你说的是你截图的第一个任务？

![qq 20180718101258](https://user-images.githubusercontent.com/5820324/42855461-33466566-8a73-11e8-8602-6a46155b1a92.png)

我看你的好像有异常。你看看。

**Comment by 846677234** [comment]
日志截图是第一个任务的
![image](https://user-images.githubusercontent.com/6667502/42855500-673ad74e-8a73-11e8-9395-8fe0300b5851.png)
异常信息是6月26号的

**Comment by zhaopeiym** [comment]
额，这个我暂时也不清楚原因。

你那边可以重现这个问题？

**Comment by 846677234** [comment]
我也找不到原因，重现应该也不好重现，我先重现安装一下吧

**Comment by zhaopeiym** [comment]
经过测试，确定无法重现。

如果是iis 会自动回收。需要另做处理。
