### ISSUE TITLE
展示任务出错

### ISSUE THREAD

**Issue by lilei2020** [zhaopeiym/quartzui#30]
当QRTZ_JOB_DETAILS表中JOB_CLASS_NAME字段存在一个与当前创建任务不同的类型时，界面不会展示数据。
出错位置在SchedulerCenter==>GetAllJobBriefInfoAsync方法的第十行。
报错信息：Couldn't retrieve job because a required type was not found: Could not load type 'XXX'

使用两套程序分别向一个数据库中创建任务时发现的这个问题。

**Comment by zhaopeiym** [comment]
我使用的是默认的SQLite持久化，如果你在使用其他数据库中遇到的问题，请自行解决。

**Comment by lilei2020** [comment]
收到，感谢回复。
