### ISSUE TITLE
app.UseCors("AllowSameDomain") 位置错误

### ISSUE THREAD

**Issue by zjc-china** [zhaopeiym/quartzui#37]
app.UseRouting();
            app.UseAuthorization();
            app.UseCors("AllowSameDomain");
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
如上，应该放在 app.UseRouting(); 和 UseEndpoints 之间

**Comment by Ran-snow** [comment]
收到

**Comment by Ran-snow** [comment]
*app.UseCors("AllowSameDomain");* 应该在 *app.UseAuthorization();* 之前

[(CORS) 启用跨域请求 ASP.NET Core](https://docs.microsoft.com/zh-cn/aspnet/core/security/cors?view=aspnetcore-3.1)

**Comment by zhaopeiym** [comment]
收到，已修改。
