### ISSUE TITLE
ConfigureServices 中跨域配置逻辑有误需要调整

### ISSUE THREAD

**Issue by zjc-china** [zhaopeiym/quartzui#38]
![image](https://user-images.githubusercontent.com/12705506/89803981-227d3700-db66-11ea-8eeb-a1193f750522.png)

**Comment by Ran-snow** [comment]
收到，这段代码好像是我改的，当时对跨域什么陌生..

**Comment by zhaopeiym** [comment]
已修复到dev分支。
