### ISSUE TITLE
任务调度数量过多的话，连接池不释放

### ISSUE THREAD

**Issue by liugt34** [zhaopeiym/quartzui#43]
Failed to obtain DB connection from data source 'default': Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise MaxPoolSize (currently 20) or Timeout (currently 15 seconds)

**Comment by zhaopeiym** [comment]
有多少任务呢？执行了多久？  我测试了下，没有出现类型情况。

**Comment by liugt34** [comment]
不到100个，80多个

**Comment by zhaopeiym** [comment]
https://scheduler_test.haojima.net   这个临时地址使用就是postgres，要不你测试下。

**Comment by zhaopeiym** [comment]
或者更新下代码试试呢？
如果还是出现此类问题，请提交issue到https://github.com/quartznet/quartznet
