### ISSUE TITLE
异常信息

### ISSUE THREAD

**Issue by taolinhui** [zhaopeiym/quartzui#54]
![image](https://user-images.githubusercontent.com/26008131/116542687-81b2ef80-a91f-11eb-891c-6dde78b93900.png)
接口并没有返回异常，但是一直会出现异常提示。

**Comment by zhaopeiym** [comment]
哪里出现了异常提示？

**Comment by taolinhui** [comment]
![image](https://user-images.githubusercontent.com/26008131/116545161-aa88b400-a922-11eb-8316-ce2ac0f434ae.png)
列表页面会先显示有异常信息。
![image](https://user-images.githubusercontent.com/26008131/116545243-c1c7a180-a922-11eb-9c85-281d9990bef8.png)
但接口是正常返回的 200的

**Comment by zhaopeiym** [comment]
按钮 “查看x” ， 你点下x，还会出现吗？

**Comment by taolinhui** [comment]
> 按钮 “查看x” ， 你点下x，还会出现吗？

会一直出现，且errormsg都是空。但是不是每次请求都会出现。

**Comment by zhaopeiym** [comment]
我不太清楚你这是什么情况，能重现下吗？https://scheduler.haojima.net/

**Comment by taolinhui** [comment]
> https://scheduler.haojima.net/

已经添加了，可以看看

**Comment by zhaopeiym** [comment]
你是部署的源码，还是直接运行docker？

**Comment by taolinhui** [comment]
> 你是部署的源码，还是直接运行docker？

直接运行的docker

**Comment by zhaopeiym** [comment]
那你稍等下，我发布下dockers。

**Comment by zhaopeiym** [comment]
1、先停止删除 quartzui 
2、运行
docker run -v /fileData/quartzuifile:/app/File  --restart=unless-stopped --privileged=true --name quartzui -dp 5088:80 bennyzhao/quartzui:5.1-alpine

**Comment by taolinhui** [comment]
> docker run -v /fileData/quartzuifile:/app/File --restart=unless-stopped --privileged=true --name quartzui -dp 5088:80 bennyzhao/quartzui:5.1-alpine

好的
