### ISSUE TITLE
HttpClient超时

### ISSUE THREAD

**Issue by 846677234** [zhaopeiym/quartzui#6]
任务执行时间很长，大概5分钟左右，HttpClient默认超时时间是100秒，可否把这个时间改为配置或者设置长一点。我找到对应的代码了，但是不知道你这边是怎么打包成docker的，所以麻烦了

**Comment by zhaopeiym** [comment]
1、超时不是影响任务的正常执行
2、你可以修改请求的地址为异步任务。Task.Run(()=>{ //这里写你的执行逻辑  
3、觉得修改时间不是很合理，也许还有更长时间的任务。不过这里可以做成可配置。
