### ISSUE TITLE
扫描下一个待触发的触发器时出错

### ISSUE THREAD

**Issue by moyaoo** [zhaopeiym/quartzui#76]
程序正常运行了一段时间，但近两天每次再早上停止运行了，不知道什么原因，错误提示如下：
[Error] An error occurred while scanning for the next trigger to fire.
Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock: SQLite Error 14: 'unable to open database file'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.Execute

**Comment by zhaopeiym** [comment]
给了提示，`unable to open database file`

**Comment by moyaoo** [comment]
由于封装了数据库操作，我想弄明白为什么打不开db文件，重启后又能正常运行，每天8点半左右就报这错，是环境原因还是并发原因

**Comment by zhaopeiym** [comment]
你用的 SQLite 还是 SQLite-Microsoft？

**Comment by moyaoo** [comment]
SQLite-Microsoft

**Comment by zhaopeiym** [comment]
我没有遇到过这个问题，线上都正常运行几年了。

**Comment by moyaoo** [comment]
麻烦你了，前几个月都是正常，就最近两天出现的，我继续观察，看能否找到原因

**Comment by zhaopeiym** [comment]
你自己试试网上找找问题`SQLite Error 14: 'unable to open database file'`的解决方案。

给db文件和对应的文件夹 写入权限，试试。
