### ISSUE TITLE
JobPersistenceException: referenced by the trigger does not exist.

### ISSUE THREAD

**Issue by ghd258** [zhaopeiym/quartzui#8]
JobPersistenceException: Couldn't store trigger 'DEFAULT.MT_2885808657110662513' for ' default.name482285245' job: The job ( default.name482285245) referenced by the trigger does not exist.

**Comment by zhaopeiym** [comment]
能否详细描述下问题？或者问题重现步骤。

**Comment by ghd258** [comment]
已解决
