### ISSUE TITLE
发布部署

### ISSUE THREAD

**Issue by huangyedie** [zhaopeiym/quartzui#89]
部署方式是不是两种
1、可以直接用.net 代码把前端打包复制到wwwroot下替换文件，这种方式是不是直接发布.net 代码。会自动把前后端都打进去了？这样启动一个docker容器是不是就可以了？
2、单独部署前后端分离。
是这样吗？

**Comment by huangyedie** [comment]
你好。还有一个问题：
当我改动了前端代码，做了biuld发布。这时候我把dist下的发布文件复制到wwwroot替换原有的文件，再启动host程序。前端会改变吗？我这里碰到的问题就是改过的前端代码没有生效，是不是我的方式有问题。帮忙解答一下谢谢

**Comment by huangyedie** [comment]
@zhaopeiym

**Comment by huangyedie** [comment]
已解决

**Comment by Git-wk** [comment]
你好，请问是怎么解决的？

**Comment by Git-wk** [comment]
> 已解决
你好，请问是怎么解决的？

**Comment by huangyedie** [comment]
我记得是把wwwroot里面都删了，把新biuld的前端放进去了。清理解决方案，重新生成，启动就好了

**Comment by huangyedie** [comment]
太久了具体操作忘记了
