### ISSUE TITLE
job一直提示接口报错，是不是我使用不对

### ISSUE THREAD

**Issue by wuxinheng** [zhaopeiym/quartzui#90]
![image](https://user-images.githubusercontent.com/49859025/196105942-c573ea3d-67a4-4627-8be8-0b0c56bd4eb9.png)

我把本地iis上部署的api跑在job上，一致是这个提示，是由返回体限制吗，我本地运行接口没有问题

@zhaopeiym

**Comment by huangyedie** [comment]
有固定格式的。你可以看一下源码。当然不按照格式也没事。

**Comment by huangyedie** [comment]
应该是IsSuccess,ErrorMsg
